# Generated by Django 5.1.4 on 2025-01-02 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_blogger_rename_author_blog_blogger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['post_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blogger',
            new_name='commentor',
        ),
    ]
